// tslint:disable
/**
 * Lappuzet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    UserDto,
} from '../models';

/**
 * no description
 */
export class UserApi extends BaseAPI {

    /**
     * Gets current user
     */
    userGet(): Observable<UserDto>
    userGet(opts?: OperationOpts): Observable<RawAjaxResponse<UserDto>>
    userGet(opts?: OperationOpts): Observable<UserDto | RawAjaxResponse<UserDto>> {
        return this.request<UserDto>({
            url: '/user',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
