// tslint:disable
/**
 * Lappuzet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GoalTreeNodeDto,
} from './';

/**
 * @export
 * @interface GoalTreeFullDto
 */
export interface GoalTreeFullDto {
    /**
     * @type {string}
     * @memberof GoalTreeFullDto
     */
    created_at: string;
    /**
     * @type {number}
     * @memberof GoalTreeFullDto
     */
    id: number;
    /**
     * @type {string}
     * @memberof GoalTreeFullDto
     */
    name: string;
    /**
     * @type {Array<GoalTreeNodeDto>}
     * @memberof GoalTreeFullDto
     */
    nodes: Array<GoalTreeNodeDto>;
}
