// tslint:disable
/**
 * Lappuzet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NewGoalTreeNodeDto
 */
export interface NewGoalTreeNodeDto {
    /**
     * @type {string}
     * @memberof NewGoalTreeNodeDto
     */
    description?: string;
    /**
     * @type {number}
     * @memberof NewGoalTreeNodeDto
     */
    parent_node?: number;
    /**
     * @type {string}
     * @memberof NewGoalTreeNodeDto
     */
    title: string;
}
