// tslint:disable
/**
 * Lappuzet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NewJournalNoteDto
 */
export interface NewJournalNoteDto {
    /**
     * @type {number}
     * @memberof NewJournalNoteDto
     */
    food: number;
    /**
     * @type {string}
     * @memberof NewJournalNoteDto
     */
    message: string;
    /**
     * @type {number}
     * @memberof NewJournalNoteDto
     */
    mood: number;
    /**
     * @type {number}
     * @memberof NewJournalNoteDto
     */
    sleep: number;
    /**
     * @type {number}
     * @memberof NewJournalNoteDto
     */
    stress: number;
}
