// tslint:disable
/**
 * Lappuzet
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NewNoteDto
 */
export interface NewNoteDto {
    /**
     * @type {string}
     * @memberof NewNoteDto
     */
    message: string;
    /**
     * @type {boolean}
     * @memberof NewNoteDto
     */
    needsResolve: boolean;
}
